name: Build and Push Docker Image
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: tyk-application
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run:
          docker build --tag $IMAGE_NAME:$(date +%s) --file ./Dockerfile .

#- name: Commit and push changes
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git commit -m "Your commit message"
#          git push origin main
